# docker-compose file to setup:
# - mysql
# - elasticsearch
# - backend: depends on mysql and elasticsearch
# - taskrunner: process background tasks
# - frontend: depends on backend
# - rendertron


services:

  mysql:
    container_name: biotools-mysql
    image: mysql:8.0.43
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=elixirroot
      - MYSQL_DATABASE=elixir
      - MYSQL_USER=elixir
      - MYSQL_PASSWORD=123
    volumes:
      - "data-mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    networks:
      - net

  elasticsearch:
    container_name: biotools-elasticsearch
    image: elasticsearch:7.12.1
    restart: unless-stopped
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - "data-elasticsearch:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - net

  backend:
    container_name: biotools-backend
    image: biotools/backend:latest
    build:
      context: ./backend
    environment:
      - BIOTOOLS_ELASTIC_SEARCH_URLS=http://elasticsearch:9200
      - BIOTOOLS_URL_FRONT=https://bio.tools/
      - BIOTOOLS_MYSQL_DB=elixir
      - BIOTOOLS_MYSQL_HOST=biotools-mysql
      - BIOTOOLS_MYSQL_PASSWORD=123
      - BIOTOOLS_MYSQL_USER=elixir
    ports:
      - "80:80"
    networks:
      - net
    depends_on:
      - mysql
      - elasticsearch
    links:
      - mysql
      - elasticsearch
    volumes:
      - backend_data:/elixir/application/backend/data

  taskrunner:
    container_name: biotools-taskrunner
    image: biotools/backend:latest
    build:
      context: ./backend
      target: dev
    environment:
      - BIOTOOLS_ELASTIC_SEARCH_URLS=http://elasticsearch:9200
      - BIOTOOLS_MYSQL_DB=elixir
      - BIOTOOLS_MYSQL_HOST=biotools-mysql
      - BIOTOOLS_MYSQL_PASSWORD=123
      - BIOTOOLS_MYSQL_USER=elixir
    networks:
      - net
    depends_on:
      - mysql
      - elasticsearch
    command: python manage.py process_tasks

  frontend:
    container_name: biotools-frontend
    image: biotools/frontend:latest
    build:
      context: ./frontend
    networks:
      - net
    depends_on:
      - backend

  rendertron:
    image: dockette/rendertron
    container_name: biotools-rendertron
    ports:
      - "3000:3000"
    networks:
      - net
    restart: unless-stopped

networks:
  net:
    name: biotools-net

volumes:
  data-mysql:
  data-elasticsearch:
  backend_data:
