# docker compose file for the biotoolsRegistry
# - mysql: MySQL database
# - elasticsearch: Elasticsearch search engine
# - biotools: bio.tools application
# - taskrunner: process background tasks
# - rendertron


services:

  mysql:
    container_name: biotools-mysql
    image: mysql:8.0.43
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
    volumes:
      - "data-mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    networks:
      - net

  elasticsearch:
    container_name: biotools-elasticsearch
    image: elasticsearch:7.12.1
    restart: unless-stopped
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - "data-elasticsearch:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - net

  biotools:
    container_name: biotools-registry
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "80:80"
    networks:
      - net
    depends_on:
      - mysql
      - elasticsearch
    links:
      - mysql
      - elasticsearch
    volumes:
      - backend_data:/elixir/application/backend/data

  taskrunner:
    container_name: biotools-taskrunner
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      target: dev
    env_file:
      - .env
    networks:
      - net
    depends_on:
      - mysql
      - elasticsearch
    command: python manage.py process_tasks

  metadata-bridge:
    container_name: biotools-metadata-bridge
    image: anitamnd/bridge:latest
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      HUGGINGFACE_TOKEN: ${HUGGINGFACE_TOKEN}
    restart: unless-stopped
    networks:
      - net

  rendertron:
    image: dockette/rendertron
    container_name: biotools-rendertron
    ports:
      - "3000:3000"
    networks:
      - net
    restart: unless-stopped

networks:
  net:
    name: biotools-net

volumes:
  data-mysql:
  data-elasticsearch:
  backend_data:
