INSERT INTO `elixir_issuetype` (`id`, `type`, `description`, `weight`, `field_name`, `attribute`, `field_value`)
VALUES
	(7, 'invalid_url', NULL, NULL, 'url', 'link', NULL),
	(8, 'invalid_url', NULL, NULL, '', 'homepage', NULL),
	(9, 'invalid_url', NULL, NULL, 'url', 'download', NULL),
	(10, 'invalid_url', NULL, NULL, 'url', 'documentation', NULL),
	(11, 'invalid_url', NULL, NULL, 'url', 'credit', NULL),
	(12, 'invalid_url', NULL, NULL, 'url', 'contact', NULL),
	(13, 'missing', NULL, NULL, 'id', 'publication', NULL),
	(14, 'missing', NULL, NULL, 'type', 'documentation', 'terms_of_use'),
	(15, 'none', NULL, NULL, 'id', 'publication', NULL),
	(16, 'missing', NULL, NULL, NULL, 'license', NULL),
	(17, 'missing', NULL, NULL, NULL, 'contact', NULL),
	(18, 'ontology', NULL, NULL, NULL, 'topic', 'Topic'),
	(19, 'ontology', NULL, NULL, NULL, 'operation', 'Operation'),
	(20, 'ontology', NULL, NULL, NULL, 'data', 'Data'),
	(21, 'ontology', NULL, NULL, NULL, 'format', 'Format'),
	(22, 'ontology', NULL, NULL, NULL, 'topic', NULL),
	(23, 'ontology', NULL, NULL, NULL, 'operation', NULL),
	(24, 'ontology', NULL, NULL, NULL, 'data', NULL),
	(25, 'ontology', NULL, NULL, NULL, 'format', NULL),
	(26, 'ontology', NULL, NULL, NULL, 'topic', 'obsolete'),
	(27, 'ontology', NULL, NULL, NULL, 'operation', 'obsolete'),
	(28, 'ontology', NULL, NULL, NULL, 'data', 'obsolete'),
	(29, 'ontology', NULL, NULL, NULL, 'format', 'obsolete'),
	(30, 'ontology', NULL, NULL, NULL, 'topic', 'not_found'),
	(31, 'ontology', NULL, NULL, NULL, 'operation', 'not_found'),
	(32, 'ontology', NULL, NULL, NULL, 'data', 'not_found'),
	(33, 'ontology', NULL, NULL, NULL, 'format', 'not_found');

