# Generated by Django 3.1.2 on 2021-05-10 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elixir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domain',
            name='visibility',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'YES')], default=1),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='domainresource',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource', to='elixir.domain'),
        ),
        migrations.CreateModel(
            name='DomainTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, null=True)),
                ('additionDate', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='elixir.domain')),
            ],
        ),
        migrations.CreateModel(
            name='DomainCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('additionDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='elixir.domain')),
            ],
        ),
    ]
