# Generated by Django 4.2.17 on 2025-03-04 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elixir', '0002_auto_20210510_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='community',
        ),
    ]
