# Generated by Django 3.1.2 on 2025-03-16 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elixir', '0002_auto_20210510_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='biolib',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='community',
        ),
        migrations.DeleteModel(
            name='BioLib',
        ),
        migrations.DeleteModel(
            name='Community',
        ),
    ]
