# Generated by Django 3.1.2 on 2025-07-23 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elixir', '0003_auto_20250316_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='editable_domains', to=settings.AUTH_USER_MODEL),
        ),
    ]
