/**
 * *****************************************************************************
 * Copyright (C) 2016 ELIXIR ES, Spanish National Bioinformatics Institute (INB)
 * and Barcelona Supercomputing Center (BSC)
 *
 * Modifications to the initial code base are copyright of their respective
 * authors, or their employers as appropriate.
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301  USA
 *****************************************************************************
 */

package es.elixir.bsc.biotools.parser.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;

/**
 *
 * @author Dmitry Repchevsky
 */

@XmlEnum(EnumType.class)
public enum LicenseType {
    @XmlEnumValue("0BSD") ZERO_BSD("0BSD"), // BSD Zero Clause License
    @XmlEnumValue("AAL") AAL("AAL"),
    @XmlEnumValue("ADSL") ADSL("ADSL"),
    @XmlEnumValue("AFL-1.1") AFL_1_1("AFL-1.1"),
    @XmlEnumValue("AFL-1.2") AFL_1_2("AFL-1.2"),
    @XmlEnumValue("AFL-2.0") AFL_2_0("AFL-2.0"),
    @XmlEnumValue("AFL-2.1") AFL_2_1("AFL-2.1"),
    @XmlEnumValue("AFL-3.0") AFL_3_0("AFL-3.0"),
    @XmlEnumValue("AMDPLPA") AMDPLPA("AMDPLPA"),
    @XmlEnumValue("AML") AML("AML"),
    @XmlEnumValue("AMPAS") AMPAS("AMPAS"),
    @XmlEnumValue("ANTLR-PD") ANTLR_PD("ANTLR-PD"),
    @XmlEnumValue("APAFML") APAFML("APAFML"),
    @XmlEnumValue("APL-1.0") APL_1_0("APL-1.0"),
    @XmlEnumValue("APSL-1.0") APSL_1_0("APSL-1.0"),
    @XmlEnumValue("APSL-1.1") APSL_1_1("APSL-1.1"),
    @XmlEnumValue("APSL-1.2") APSL_1_2("APSL-1.2"),
    @XmlEnumValue("APSL-2.0") APSL_2_0("APSL-2.0"),
    @XmlEnumValue("Abstyles") ABSTYLES("Abstyles"),
    @XmlEnumValue("Adobe-2006") ADOBE_2006("Adobe-2006"),
    @XmlEnumValue("Adobe-Glyph") ADOBE_GLYPH("Adobe-Glyph"),
    @XmlEnumValue("Afmparse") AFMPARSE("Afmparse"),
    @XmlEnumValue("Aladdin") ALADDIN("Aladdin"),
    @XmlEnumValue("Apache-1.0") APACHE_1_0("Apache-1.0"),
    @XmlEnumValue("Apache-1.1") APACHE_1_1("Apache-1.1"),
    @XmlEnumValue("Apache-2.0") APACHE_2_0("Apache-2.0"),
    @XmlEnumValue("Artistic-1.0") ARTISTIC_1_0("Artistic-1.0"),
    @XmlEnumValue("Artistic-1.0-Perl") ARTISTIC_1_0_PERL("Artistic-1.0-Perl"),
    @XmlEnumValue("Artistic-1.0-cl8") ARTISTIC_1_0_CL8("Artistic-1.0-cl8"),
    @XmlEnumValue("Artistic-2.0") ARTISTIC_2_0("Artistic-2.0"),
    @XmlEnumValue("BSD-2-Clause") BSD_2_CLAUSE("BSD-2-Clause"),
    @XmlEnumValue("BSD-2-Clause-FreeBSD") BSD_2_CLAUSE_FREEBSD("BSD-2-Clause-FreeBSD"),
    @XmlEnumValue("BSD-2-Clause-NetBSD") BSD_2_CLAUSE_NETBSD("BSD-2-Clause-NetBSD"),
    @XmlEnumValue("BSD-3-Clause") BSD_3_CLAUSE("BSD-3-Clause"),
    @XmlEnumValue("BSD-3-Clause-Attribution") BSD_3_CLAUSE_ATTRIBUTION("BSD-3-Clause-Attribution"),
    @XmlEnumValue("BSD-3-Clause-Clear") BSD_3_CLAUSE_CLEAR("BSD-3-Clause-Clear"),
    @XmlEnumValue("BSD-3-Clause-LBNL") BSD_3_CLAUSE_LBNL("BSD-3-Clause-LBNL"),
    @XmlEnumValue("BSD-3-Clause-No-Nuclear-License") BSD_3_CLAUSE_NO_NUCLEAR_LICENSE("BSD-3-Clause-No-Nuclear-License"),
    @XmlEnumValue("BSD-3-Clause-No-Nuclear-License-2014") BSD_3_CLAUSE_NO_NUCLEAR_LICENSE_2014("BSD-3-Clause-No-Nuclear-License-2014"),
    @XmlEnumValue("BSD-3-Clause-No-Nuclear-Warranty") BSD_3_CLAUSE_NO_NUCLEAR_WARRANTY("BSD-3-Clause-No-Nuclear-Warranty"),
    @XmlEnumValue("BSD-4-Clause") BSD_4_CLAUSE("BSD-4-Clause"),
    @XmlEnumValue("BSD-4-Clause-UC") BSD_4_CLAUSE_UC("BSD-4-Clause-UC"),
    @XmlEnumValue("BSD-Protection") BSD_PROTECTION("BSD-Protection"),
    @XmlEnumValue("BSD-Source-Code") BSD_SOURCE_CODE("BSD-Source-Code"),
    @XmlEnumValue("BSL-1.0") BSL_1_0("BSL-1.0"),
    @XmlEnumValue("Bahyph") BAHYTH("Bahyph"),
    @XmlEnumValue("Barr") BARR("Barr"),
    @XmlEnumValue("Beerware") BEERWARE("Beerware"),
    @XmlEnumValue("BitTorrent-1.0") BITTORRENT_1_0("BitTorrent-1.0"),
    @XmlEnumValue("BitTorrent-1.1") BITTORRENT_1_1("BitTorrent-1.1"),
    @XmlEnumValue("Borceux") BORCEUX("Borceux"),
    @XmlEnumValue("CATOSL-1.1") CATOSL_1_1("CATOSL-1.1"),
    @XmlEnumValue("CC-BY-1.0") CC_BY_1_0("CC-BY-1.0"),
    @XmlEnumValue("CC-BY-2.0") CC_BY_2_0("CC-BY-2.0"),
    @XmlEnumValue("CC-BY-2.5") CC_BY_2_5("CC-BY-2.5"),
    @XmlEnumValue("CC-BY-3.0") CC_BY_3_0("CC-BY-3.0"),
    @XmlEnumValue("CC-BY-4.0") CC_BY_4_0("CC-BY-4.0"),
    @XmlEnumValue("CC-BY-NC-1.0") CC_BY_NC_1_0("CC-BY-NC-1.0"),
    @XmlEnumValue("CC-BY-NC-2.0") CC_BY_NC_2_0("CC-BY-NC-2.0"),
    @XmlEnumValue("CC-BY-NC-2.5") CC_BY_NC_2_5("CC-BY-NC-2.5"),
    @XmlEnumValue("CC-BY-NC-3.0") CC_BY_NC_3_0("CC-BY-NC-3.0"),
    @XmlEnumValue("CC-BY-NC-4.0") CC_BY_NC_4_0("CC-BY-NC-4.0"),
    @XmlEnumValue("CC-BY-NC-ND-1.0") CC_BY_NC_ND_1_0("CC-BY-NC-ND-1.0"),
    @XmlEnumValue("CC-BY-NC-ND-2.0") CC_BY_NC_ND_2_0("CC-BY-NC-ND-2.0"),
    @XmlEnumValue("CC-BY-NC-ND-2.5") CC_BY_NC_ND_2_5("CC-BY-NC-ND-2.5"),
    @XmlEnumValue("CC-BY-NC-ND-3.0") CC_BY_NC_ND_3_0("CC-BY-NC-ND-3.0"),
    @XmlEnumValue("CC-BY-NC-ND-4.0") CC_BY_NC_ND_4_0("CC-BY-NC-ND-4.0"),
    @XmlEnumValue("CC-BY-NC-SA-1.0") CC_BY_NC_SA_1_0("CC-BY-NC-SA-1.0"),
    @XmlEnumValue("CC-BY-NC-SA-2.0") CC_BY_NC_SA_2_0("CC-BY-NC-SA-2.0"),
    @XmlEnumValue("CC-BY-NC-SA-2.5") CC_BY_NC_SA_2_5("CC-BY-NC-SA-2.5"),
    @XmlEnumValue("CC-BY-NC-SA-3.0") CC_BY_NC_SA_3_0("CC-BY-NC-SA-3.0"),
    @XmlEnumValue("CC-BY-NC-SA-4.0") CC_BY_NC_SA_4_0("CC-BY-NC-SA-4.0"),
    @XmlEnumValue("CC-BY-ND-1.0") CC_BY_ND_1_0("CC-BY-ND-1.0"),
    @XmlEnumValue("CC-BY-ND-2.0") CC_BY_ND_2_0("CC-BY-ND-2.0"),
    @XmlEnumValue("CC-BY-ND-2.5") CC_BY_ND_2_5("CC-BY-ND-2.5"),
    @XmlEnumValue("CC-BY-ND-3.0") CC_BY_ND_3_0("CC-BY-ND-3.0"),
    @XmlEnumValue("CC-BY-ND-4.0") CC_BY_ND_4_0("CC-BY-ND-4.0"),
    @XmlEnumValue("CC-BY-SA-1.0") CC_BY_SA_1_0("CC-BY-SA-1.0"),
    @XmlEnumValue("CC-BY-SA-2.0") CC_BY_SA_2_0("CC-BY-SA-2.0"),
    @XmlEnumValue("CC-BY-SA-2.5") CC_BY_SA_2_5("CC-BY-SA-2.5"),
    @XmlEnumValue("CC-BY-SA-3.0") CC_BY_SA_3_0("CC-BY-SA-3.0"),
    @XmlEnumValue("CC-BY-SA-4.0") CC_BY_SA_4_0("CC-BY-SA-4.0"),
    @XmlEnumValue("CC0-1.0") CC0_1_0("CC0-1.0"),
    @XmlEnumValue("CDDL-1.0") CDDL_1_0("CDDL-1.0"),
    @XmlEnumValue("CDDL-1.1") CDDL_1_1("CDDL-1.1"),
    @XmlEnumValue("CECILL-1.0") CECILL_1_0("CECILL-1.0"),
    @XmlEnumValue("CECILL-1.1") CECILL_1_1("CECILL-1.1"),
    @XmlEnumValue("CECILL-2.0") CECILL_2_0("CECILL-2.0"),
    @XmlEnumValue("CECILL-2.1") CECILL_2_1("CECILL-2.1"),
    @XmlEnumValue("CECILL-B") CECILL_B("CECILL-B"),
    @XmlEnumValue("CECILL-C") CECILL_C("CECILL-C"),
    @XmlEnumValue("CNRI-Jython") CNRI_JYTHON("CNRI-Jython"),
    @XmlEnumValue("CNRI-Python") CNRI_PYTHON("CNRI-Python"),
    @XmlEnumValue("CNRI-Python-GPL-Compatible") CNRI_PYTHON_GPL_COMPATIBLE("CNRI-Python-GPL-Compatible"),
    @XmlEnumValue("CPAL-1.0") CPAL_1_0("CPAL-1.0"),
    @XmlEnumValue("CPL-1.0") CPL_1_0("CPL-1.0"),
    @XmlEnumValue("CPOL-1.02") CPOL_1_02("CPOL-1.02"),
    @XmlEnumValue("CUA-OPL-1.0") CUA_OPL_1_0("CUA-OPL-1.0"),
    @XmlEnumValue("Caldera") CALDERA("Caldera"),
    @XmlEnumValue("ClArtistic") CLARTISTIC("ClArtistic"),
    @XmlEnumValue("Condor-1.1") CONDOR_1_1("Condor-1.1"),
    @XmlEnumValue("Crossword") CROSSWORD("Crossword"),
    @XmlEnumValue("CrystalStacker") CRISTAL_STACKER("CrystalStacker"),
    @XmlEnumValue("Cube") CUBE("Cube"),
    @XmlEnumValue("D-FSL-1.0") D_FSL_1_0("D-FSL-1.0"),
    @XmlEnumValue("DOC") DOC("DOC"),
    @XmlEnumValue("DSDP") DSDP("DSDP"),
    @XmlEnumValue("Dotseqn") DOTSEQN("Dotseqn"),
    @XmlEnumValue("ECL-1.0") ECL_1_0("ECL-1.0"),
    @XmlEnumValue("ECL-2.0") ECL_2_0("ECL-2.0"),
    @XmlEnumValue("EFL-1.0") EFL_1_0("EFL-1.0"),
    @XmlEnumValue("EFL-2.0") EFL_2_0("EFL-2.0"),
    @XmlEnumValue("EPL-1.0") EPL_1_0("EPL-1.0"),
    @XmlEnumValue("EUDatagrid") EU_DATAGRID("EUDatagrid"),
    @XmlEnumValue("EUPL-1.0") EUPL_1_0("EUPL-1.0"),
    @XmlEnumValue("EUPL-1.1") EUPL_1_1("EUPL-1.1"),
    @XmlEnumValue("Entessa") ENTESSA("Entessa"),
    @XmlEnumValue("ErlPL-1.1") ERLPL_1_1("ErlPL-1.1"),
    @XmlEnumValue("Eurosym") EUROSYM("Eurosym"),
    @XmlEnumValue("FSFAP") FSFAP("FSFAP"),
    @XmlEnumValue("FSFUL") FSFUL("FSFUL"),
    @XmlEnumValue("FSFULLR") FSFULLR("FSFULLR"),
    @XmlEnumValue("FTL") FTL("FTL"),
    @XmlEnumValue("Fair") FAIR("Fair"),
    @XmlEnumValue("Frameworx-1.0") FRAMEWORX_1_0("Frameworx-1.0"),
    @XmlEnumValue("FreeImage") FREE_IMAGE("FreeImage"),
    @XmlEnumValue("GFDL-1.1") GFDL_1_1("GFDL-1.1"),
    @XmlEnumValue("GFDL-1.2") GFDL_1_2("GFDL-1.2"),
    @XmlEnumValue("GFDL-1.3") GFDL_1_3("GFDL-1.3"),
    @XmlEnumValue("GL2PS") GL2PS("GL2PS"),
    @XmlEnumValue("GPL-1.0") GPL_1_0("GPL-1.0"),
    @XmlEnumValue("GPL-2.0") GPL_2_0("GPL-2.0"),
    @XmlEnumValue("GPL-3.0") GPL_3_0("GPL-3.0"),
    @XmlEnumValue("Giftware") GIFTWARE("Giftware"),
    @XmlEnumValue("Glide") GLIDE("Glide"),
    @XmlEnumValue("Glulxe") GLULXE("Glulxe"),
    @XmlEnumValue("HPND") HPND("HPND"),
    @XmlEnumValue("HaskellReport") HASKELL_REPORT("HaskellReport"),
    @XmlEnumValue("IBM-pibs") IBM_PIBS("IBM-pibs"),
    @XmlEnumValue("ICU") ICU("ICU"),
    @XmlEnumValue("IJG") IJG("IJG"),
    @XmlEnumValue("IPA") IPA("IPA"),
    @XmlEnumValue("IPL-1.0") IPL_1_0("IPL-1.0"),
    @XmlEnumValue("ISC") ISC("ISC"),
    @XmlEnumValue("ImageMagick") IMAGE_MAGICK("ImageMagick"),
    @XmlEnumValue("Imlib2") IMLIB2("Imlib2"),
    @XmlEnumValue("Info-ZIP") INFO_ZIP("Info-ZIP"),
    @XmlEnumValue("Intel") INTEL("Intel"),
    @XmlEnumValue("Intel-ACPI") INTEL_ACPI("Intel-ACPI"),
    @XmlEnumValue("Interbase-1.0") INTERBASE_1_0("Interbase-1.0"),
    @XmlEnumValue("JSON") JSON("JSON"),
    @XmlEnumValue("JasPer-2.0") JASPER_2_0("JasPer-2.0"),
    @XmlEnumValue("LAL-1.2") LAL_1_2("LAL-1.2"),
    @XmlEnumValue("LAL-1.3") LAL_1_3("LAL-1.3"),
    @XmlEnumValue("LGPL-2.0") LGPL_2_0("LGPL-2.0"),
    @XmlEnumValue("LGPL-2.1") LGPL_2_1("LGPL-2.1"),
    @XmlEnumValue("LGPL-3.0") LGPL_3_0("LGPL-3.0"),
    @XmlEnumValue("LGPLLR") LGPLLR("LGPLLR"),
    @XmlEnumValue("LPL-1.0") LPL_1_0("LPL-1.0"),
    @XmlEnumValue("LPL-1.02") LPL_1_02("LPL-1.02"),
    @XmlEnumValue("LPPL-1.0") LPPL_1_0("LPPL-1.0"),
    @XmlEnumValue("LPPL-1.1") LPPL_1_1("LPPL-1.1"),
    @XmlEnumValue("LPPL-1.2") LPPL_1_2("LPPL-1.2"),
    @XmlEnumValue("LPPL-1.3a") LPPL_1_3A("LPPL-1.3a"),
    @XmlEnumValue("LPPL-1.3c") LPPL_1_3C("LPPL-1.3c"),
    @XmlEnumValue("Latex2e") LATEX_2E("Latex2e"),
    @XmlEnumValue("Leptonica") LEPTONICA("Leptonica"),
    @XmlEnumValue("LiLiQ-P-1.1") LILIQ_P_1_1("LiLiQ-P-1.1"),
    @XmlEnumValue("LiLiQ-R-1.1") LILIQ_R_1_1("LiLiQ-R-1.1"),
    @XmlEnumValue("LiLiQ-Rplus-1.1") LILIQ_RPLUS_1_1("LiLiQ-Rplus-1.1"),
    @XmlEnumValue("Libpng") LIBPNG("Libpng"),
    @XmlEnumValue("MIT") MIT("MIT"),
    @XmlEnumValue("MIT-CMU") MIT_CMD("MIT-CMU"),
    @XmlEnumValue("MIT-advertising") MIT_ADVERTISING("MIT-advertising"),
    @XmlEnumValue("MIT-enna") MIT_ENNA("MIT-enna"),
    @XmlEnumValue("MIT-feh") MIT_FEH("MIT-feh"),
    @XmlEnumValue("MITNFA") MITNFA("MITNFA"),
    @XmlEnumValue("MPL-1.0") MPL_1_0("MPL-1.0"),
    @XmlEnumValue("MPL-1.1") MPL_1_1("MPL-1.1"),
    @XmlEnumValue("MPL-2.0") MPL_2_0("MPL-2.0"),
    @XmlEnumValue("MPL-2.0-no-copyleft-exception") MPL_2_0_NO_COPYLEFT_EXCEPTION("MPL-2.0-no-copyleft-exception"),
    @XmlEnumValue("MS-PL") MS_PL("MS-PL"),
    @XmlEnumValue("MS-RL") MS_RL("MS-RL"),
    @XmlEnumValue("MTLL") MTLL("MTLL"),
    @XmlEnumValue("MakeIndex") MAKE_INDEX("MakeIndex"),
    @XmlEnumValue("MirOS") MIR_OS("MirOS"),
    @XmlEnumValue("Motosoto") MOTOSOTO("Motosoto"),
    @XmlEnumValue("Multics") MULTICS("Multics"),
    @XmlEnumValue("Mup") MUP("Mup"),
    @XmlEnumValue("NASA-1.3") NASA_1_3("NASA-1.3"),
    @XmlEnumValue("NBPL-1.0") NBPL_1_0("NBPL-1.0"),
    @XmlEnumValue("NCSA") NCSA("NCSA"),
    @XmlEnumValue("NGPL") NGPL("NGPL"),
    @XmlEnumValue("NLOD-1.0") NLOD_1_0("NLOD-1.0"),
    @XmlEnumValue("NLPL") NLPL("NLPL"),
    @XmlEnumValue("NOSL") NOSL("NOSL"),
    @XmlEnumValue("NPL-1.0") NPL_1_0("NPL-1.0"),
    @XmlEnumValue("NPL-1.1") NPL_1_1("NPL-1.1"),
    @XmlEnumValue("NPOSL-3.0") NPOSL_3_0("NPOSL-3.0"),
    @XmlEnumValue("NRL") NRL("NRL"),
    @XmlEnumValue("NTP") NTP("NTP"),
    @XmlEnumValue("Naumen") NAUMEN("Naumen"),
    @XmlEnumValue("NetCDF") NET_CDF("NetCDF"),
    @XmlEnumValue("Newsletr") NEWSLETR("Newsletr"),
    @XmlEnumValue("Nokia") NOKIA("Nokia"),
    @XmlEnumValue("Noweb") NOWEB("Noweb"),
    @XmlEnumValue("Nunit") NUNIT("Nunit"),
    @XmlEnumValue("OCCT-PL") OCCT_PL("OCCT-PL"),
    @XmlEnumValue("OCLC-2.0") OCLC_2_0("OCLC-2.0"),
    @XmlEnumValue("ODbL-1.0") ODBL_1_0("ODbL-1.0"),
    @XmlEnumValue("OFL-1.0") OFL_1_0("OFL-1.0"),
    @XmlEnumValue("OFL-1.1") OFL_1_1("OFL-1.1"),
    @XmlEnumValue("OGTSL") OGTSL("OGTSL"),
    @XmlEnumValue("OLDAP-1.1") OLDAP_1_1("OLDAP-1.1"),
    @XmlEnumValue("OLDAP-1.2") OLDAP_1_2("OLDAP-1.2"),
    @XmlEnumValue("OLDAP-1.3") OLDAP_1_3("OLDAP-1.3"),
    @XmlEnumValue("OLDAP-1.4") OLDAP_1_4("OLDAP-1.4"),
    @XmlEnumValue("OLDAP-2.0") OLDAP_2_0("OLDAP-2.0"),
    @XmlEnumValue("OLDAP-2.0.1") OLDAP_2_0_1("OLDAP-2.0.1"),
    @XmlEnumValue("OLDAP-2.1") OLDAP_2_1("OLDAP-2.1"),
    @XmlEnumValue("OLDAP-2.2") OLDAP_2_2("OLDAP-2.2"),
    @XmlEnumValue("OLDAP-2.2.1") OLDAP_2_2_1("OLDAP-2.2.1"),
    @XmlEnumValue("OLDAP-2.2.2") OLDAP_2_2_2("OLDAP-2.2.2"),
    @XmlEnumValue("OLDAP-2.3") OLDAP_2_3("OLDAP-2.3"),
    @XmlEnumValue("OLDAP-2.4") OLDAP_2_4("OLDAP-2.4"),
    @XmlEnumValue("OLDAP-2.5") OLDAP_2_5("OLDAP-2.5"),
    @XmlEnumValue("OLDAP-2.6") OLDAP_2_6("OLDAP-2.6"),
    @XmlEnumValue("OLDAP-2.7") OLDAP_2_7("OLDAP-2.7"),
    @XmlEnumValue("OLDAP-2.8") OLDAP_2_8("OLDAP-2.8"),
    @XmlEnumValue("OML") OML("OML"),
    @XmlEnumValue("OPL-1.0") OPL_1_0("OPL-1.0"),
    @XmlEnumValue("OSET-PL-2.1") OSET_PL_2_1("OSET-PL-2.1"),
    @XmlEnumValue("OSL-1.0") OSL_1_0("OSL-1.0"),
    @XmlEnumValue("OSL-1.1") OSL_1_1("OSL-1.1"),
    @XmlEnumValue("OSL-2.0") OSL_2_0("OSL-2.0"),
    @XmlEnumValue("OSL-2.1") OSL_2_1("OSL-2.1"),
    @XmlEnumValue("OSL-3.0") OSL_3_0("OSL-3.0"),
    @XmlEnumValue("OpenSSL") OPEN_SSL("OpenSSL"),
    @XmlEnumValue("PDDL-1.0") PDDL_1_0("PDDL-1.0"),
    @XmlEnumValue("PHP-3.0") PHP_3_0("PHP-3.0"),
    @XmlEnumValue("PHP-3.01") PHP_3_01("PHP-3.01"),
    @XmlEnumValue("Plexus") PLEXUS("Plexus"),
    @XmlEnumValue("PostgreSQL") POSTGRESQL("PostgreSQL"),
    @XmlEnumValue("Python-2.0") PYTHON_2_0("Python-2.0"),
    @XmlEnumValue("QPL-1.0") QPL_1_0("QPL-1.0"),
    @XmlEnumValue("Qhull") QHULL("Qhull"),
    @XmlEnumValue("RHeCos-1.1") RHECOS_1_1("RHeCos-1.1"),
    @XmlEnumValue("RPL-1.1") RPL_1_1("RPL-1.1"),
    @XmlEnumValue("RPL-1.5") RPL_1_5("RPL-1.5"),
    @XmlEnumValue("RPSL-1.0") RPSL_1_0("RPSL-1.0"),
    @XmlEnumValue("RSA-MD") RSA_MD("RSA-MD"),
    @XmlEnumValue("RSCPL") RSCPL("RSCPL"),
    @XmlEnumValue("Rdisc") RDISC("Rdisc"),
    @XmlEnumValue("Ruby") RUBY("Ruby"),
    @XmlEnumValue("SAX-PD") SAX_PD("SAX-PD"),
    @XmlEnumValue("SCEA") SCEA("SCEA"),
    @XmlEnumValue("SGI-B-1.0") SGI_B_1_0("SGI-B-1.0"),
    @XmlEnumValue("SGI-B-1.1") SGI_B_1_1("SGI-B-1.1"),
    @XmlEnumValue("SGI-B-2.0") SGI_B_2_0("SGI-B-2.0"),
    @XmlEnumValue("SISSL") SISSL("SISSL"),
    @XmlEnumValue("SISSL-1.2") SISSL_1_2("SISSL-1.2"),
    @XmlEnumValue("SMLNJ") SMLNJ("SMLNJ"),
    @XmlEnumValue("SMPPL") SMPPL("SMPPL"),
    @XmlEnumValue("SNIA") SNIA("SNIA"),
    @XmlEnumValue("SPL-1.0") SPL_1_0("SPL-1.0"),
    @XmlEnumValue("SWL") SWL("SWL"),
    @XmlEnumValue("Saxpath") SAXPATH("Saxpath"),
    @XmlEnumValue("Sendmail") SENDMAIL("Sendmail"),
    @XmlEnumValue("SimPL-2.0") SIMPL_2_0("SimPL-2.0"),
    @XmlEnumValue("Sleepycat") SLEEPYCAT("Sleepycat"),
    @XmlEnumValue("Spencer-86") SPENCER_86("Spencer-86"),
    @XmlEnumValue("Spencer-94") SPENCER_94("Spencer-94"),
    @XmlEnumValue("Spencer-99") SPENCER_99("Spencer-99"),
    @XmlEnumValue("SugarCRM-1.1.3") SUGAR_CRM_1_1_3("SugarCRM-1.1.3"),
    @XmlEnumValue("TCL") TCL("TCL"),
    @XmlEnumValue("TMate") DMATE("TMate"),
    @XmlEnumValue("TORQUE-1.1") TORQUE_1_1("TORQUE-1.1"),
    @XmlEnumValue("TOSL") TOSL("TOSL"),
    @XmlEnumValue("UPL-1.0") UPL_1_0("UPL-1.0"),
    @XmlEnumValue("Unicode-TOU") UNICODE_TOU("Unicode-TOU"),
    @XmlEnumValue("Unlicense") UNLICENSE("Unlicense"),
    @XmlEnumValue("VOSTROM") VOSTROM("VOSTROM"),
    @XmlEnumValue("VSL-1.0") VSL_1_0("VSL-1.0"),
    @XmlEnumValue("Vim") VIM("Vim"),
    @XmlEnumValue("W3C") W3C("W3C"),
    @XmlEnumValue("W3C-19980720") W3C_19980720("W3C-19980720"),
    @XmlEnumValue("WTFPL") WTFPL("WTFPL"),
    @XmlEnumValue("Watcom-1.0") WATCOM_1_0("Watcom-1.0"),
    @XmlEnumValue("Wsuipa") WSUIPA("Wsuipa"),
    @XmlEnumValue("X11") X11("X11"),
    @XmlEnumValue("XFree86-1.1") XFREE86_1_1("XFree86-1.1"),
    @XmlEnumValue("XSkat") XSKAT("XSkat"),
    @XmlEnumValue("Xerox") XEROX("Xerox"),
    @XmlEnumValue("Xnet") XNET("Xnet"),
    @XmlEnumValue("YPL-1.0") YPL_1_0("YPL-1.0"),
    @XmlEnumValue("YPL-1.1") YPL_1_1("YPL-1.1"),
    @XmlEnumValue("ZPL-1.1") ZPL_1_1("ZPL-1.1"),
    @XmlEnumValue("ZPL-2.0") ZPL_2_0("ZPL-2.0"),
    @XmlEnumValue("ZPL-2.1") ZPL_2_1("ZPL-2.1"),
    @XmlEnumValue("Zed") ZED("Zed"),
    @XmlEnumValue("Zend-2.0") ZEND_2_0("Zend-2.0"),
    @XmlEnumValue("Zimbra-1.3") ZIMBRA_1_3("Zimbra-1.3"),
    @XmlEnumValue("Zimbra-1.4") ZIMBRA_1_4("Zimbra-1.4"),
    @XmlEnumValue("Zlib") ZLIB("Zlib"),
    @XmlEnumValue("bzip2-1.0.5") BZIP2_1_0_5("bzip2-1.0.5"),
    @XmlEnumValue("bzip2-1.0.6") BZIP2_1_0_6("bzip2-1.0.6"),
    @XmlEnumValue("curl") CURL("curl"),
    @XmlEnumValue("diffmark") DIFFMARK("diffmark"),
    @XmlEnumValue("dvipdfm") DVIPDFM("dvipdfm"),
    @XmlEnumValue("eGenix") EGENIX("eGenix"),
    @XmlEnumValue("gSOAP-1.3b") GSOAP_1_3B("gSOAP-1.3b"),
    @XmlEnumValue("gnuplot") GNUPLOT("gnuplot"),
    @XmlEnumValue("iMatix") ITATIX("iMatix"),
    @XmlEnumValue("libtiff") LIBTIFF("libtiff"),
    @XmlEnumValue("mpich2") MPICH2("mpich2"),
    @XmlEnumValue("psfrag") PSFRAG("psfrag"),
    @XmlEnumValue("psutils") PSUTILS("psutils"),
    @XmlEnumValue("xinetd") XINETD("xinetd"),
    @XmlEnumValue("xpp") XPP("xpp"),
    @XmlEnumValue("zlib-acknowledgement") ZLIB_ACKNOWLEDGEMENT("zlib-acknowledgement"),
    @XmlEnumValue("Proprietary") PROPRIETARY("Proprietary"),
    @XmlEnumValue("Other") OTHER("Other");
    
    private final String value;
    
    private LicenseType(String value) {
        this.value = value;
    }
    
    @Override
    public String toString() {
        return value;
    }

    public static LicenseType fromValue(String value) {
        for (LicenseType type: LicenseType.values()) {
            if (type.value.equals(value)) {
                return type;
            }
        }
        throw new IllegalArgumentException(value);
    }
}
